name: ECS Deploy
description: Deploy to ECS
author: https://github.com/buildkite
requirements:
  - aws
  - jq
configuration:
  properties:
    cluster:
      type: string
    container-definitions:
      type: string
    env:
      type: array
    execution-role:
      type: string
    image:
      type: [ string, array ]
    region:
      type: string
    service:
      type: string
    task-cpu:
      type: integer
    task-ephemeral-storage:
      type: integer
    task-ipc-mode:
      type: string
      enum: [ "host", "none", "task"]
    task-family:
      type: string
    task-memory:
      type: integer
    task-network-mode:
      type: string
      enum: [ "awsvpc", "bridge", "host", "none" ]
    task-pid-mode:
      type: string
      enum: [ "host", "task" ]
    task-role-arn:
      type: string
  required:
    - cluster
    - service
    - task-family
    - image
