name: ECS Deploy
description: Deploy to ECS
author: https://github.com/envato
requirements:
  - aws
  - docker
configuration:
  properties:
    deploy:
      type: string
    validate:
      type: string
  oneOf:
    - required:
      - deploy
    - required:
      - validate
