steps:
  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v4.9.0:
        run: tests

  - label: ":shell: Lint"
    plugins:
      plugin-linter#v3.0.0:
        id: ecs-deploy

  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.3.0:
        files:
          - hooks/**
          - lib/**
