steps:
  - label: ":docker: :hammer:"
    plugins:
      - plugin-tester#v1.2.0: ~

  - label: ":shell: Lint"
    plugins:
      plugin-linter#v3.3.0:
        id: ecs-deploy

  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.4.0:
        files:
          - hooks/**
          - lib/**
