steps:
  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v3.3.0:
        run: tests

  - label: ":shell: Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: ecs-deploy

  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.2:
        files: hooks/**
