#!/bin/bash
set -euo pipefail

function error() {
  echo "$1"
  exit "$2"
}

function auth_ecr() {
  local docker_login
  docker_login=$(aws ecr get-login --no-include-email)
  if ! eval "${docker_login}"; then
    error "Unable to log in to ECR" 2
  fi
}

deploy_config=${BUILDKITE_PLUGIN_ECS_DEPLOY_DEPLOY_CONFIG:-""}
validate_config=${BUILDKITE_PLUGIN_ECS_DEPLOY_VALIDATE_CONFIG:-""}

if [[ -z "${deploy_config}" && -z "${validate_config}" ]] || [[ -e "${deploy_config}" && -e "${validate_config}" ]]; then
  error "One of either validate or deploy must be specified. See (TBA) for examples" 1
fi

auth_ecr

if [[ -e "${deploy_config}" ]]; then
  deploy_service "${deploy_config}"
fi

if [[ -e "${validate_config}" ]]; then
  validate_service "${validate_config}"
fi


function deploy_service() {
  docker run --rm --tty -v "$(pwd)":/app -w /app 909551307430.dkr.ecr.us-east-1.amazonaws.com/ecs-toolkit:latest deploy -c "${1}" --ci
}

function validate_service() {
  docker run --rm --tty 909551307430.dkr.ecr.us-east-1.amazonaws.com/ecs-toolkit:latest validate -c "${1}"
}
